import sys
import os

# The list of santhes generated previously
santhes_list = [
    ('1', 'Dharwad Santhe', 'Dharwad', 'Calendar.TUESDAY', 'Authentic Pedha & Hubli-Dharwad Jowar Roti', 15.4589, 75.0078),
    ('2', 'Gokak Weekly Market', 'Gokak', 'Calendar.FRIDAY', 'Gokak Karadantu & Hand-woven towels', 16.1667, 74.8333),
    ('3', 'Sirsi Spice Market', 'Sirsi', 'Calendar.SUNDAY', 'Pure Honey & Arecanut products', 14.6195, 74.8441),
    ('4', 'Byadgi Chilli Market', 'Byadgi', 'Calendar.MONDAY', 'Byadgi Red Chillies (Dabbi & Kaddi)', 14.6833, 75.4833),
    ('5', 'Ilkal Handloom Santhe', 'Ilkal', 'Calendar.THURSDAY', 'Traditional Ilkal Saris & Kasuti work', 15.9667, 76.1167),
    ('6', 'Sagar Woodcraft Market', 'Sagar', 'Calendar.WEDNESDAY', 'Sandalwood carvings & Ivory works', 14.1667, 75.0333),
    ('7', 'Mysuru Silk Santhe', 'Mysuru', 'Calendar.SATURDAY', 'Mysore Silk Saris & Sandalwood Oil', 12.3023, 76.6393),
    ('8', 'Kundapura Shandy', 'Kundapura', 'Calendar.SATURDAY', 'Fresh Sea Fish & Coastal Spices', 13.6261, 74.6917),
    ('9', 'Honnavar Weekly Market', 'Honnavar', 'Calendar.FRIDAY', 'Dry Fish & Coconut products', 14.28, 74.45),
    ('10', 'Kumta Tuesday Santhe', 'Kumta', 'Calendar.TUESDAY', 'Handicrafts & Local Vegetables', 14.43, 74.41),
    ('11', 'Ankola Wednesday Bazaar', 'Ankola', 'Calendar.WEDNESDAY', 'Ishaad Mangoes & Cashews', 14.66, 74.3),
    ('12', 'Bhatkal Sunday Shandy', 'Bhatkal', 'Calendar.SUNDAY', 'Gulf-imported goods & Traditional snacks', 13.98, 74.55),
    ('13', 'Karwar Sunday Market', 'Karwar', 'Calendar.SUNDAY', 'Fresh Seafood & Muslin cloth', 14.81, 74.13),
    ('14', 'Siddapur Spice Santhe', 'Siddapur', 'Calendar.TUESDAY', 'Cardamom & Pepper', 14.33, 74.88),
    ('15', 'Yellapur Forest Market', 'Yellapur', 'Calendar.WEDNESDAY', 'Forest Honey & Wild Berries', 14.96, 74.71),
    ('16', 'Haliyal Friday Bazaar', 'Haliyal', 'Calendar.FRIDAY', 'Timber products & Jaggery', 15.33, 74.76),
    ('17', 'Dandeli Monday Shandy', 'Dandeli', 'Calendar.MONDAY', 'Bamboo crafts & Tribal jewelry', 15.24, 74.62),
    ('18', 'Mundgod Thursday Market', 'Mundgod', 'Calendar.THURSDAY', 'Tibetan artifacts & Maize', 14.97, 75.03),
    ('19', 'Banavasi Temple Santhe', 'Banavasi', 'Calendar.THURSDAY', 'Temple artifacts & Pineapple', 14.53, 75.01),
    ('20', 'Joida Friday Bazaar', 'Joida', 'Calendar.FRIDAY', 'Root vegetables & Bamboo shoots', 15.16, 74.48),
    ('21', 'Belagavi Saturday Market', 'Belagavi', 'Calendar.SATURDAY', 'Kunda (Sweet) & Brass utensils', 15.8491, 74.4977),
    ('22', 'Athani Sunday Santhe', 'Athani', 'Calendar.SUNDAY', 'Leather Footwear (Chappals)', 16.73, 75.06),
    ('23', 'Bailahongal Monday Bazaar', 'Bailahongal', 'Calendar.MONDAY', 'Cotton & Agricultural implements', 15.82, 74.86),
    ('24', 'Chikkodi Wednesday Market', 'Chikkodi', 'Calendar.WEDNESDAY', 'Betel leaves & Sugarcane', 16.43, 74.6),
    ('25', 'Nippani Thursday Shandy', 'Nippani', 'Calendar.THURSDAY', 'Tobacco & Bidi leaves', 16.4, 74.38),
    ('26', 'Ramdurg Sunday Bazaar', 'Ramdurg', 'Calendar.SUNDAY', 'Jowar & Handloom fabrics', 15.95, 75.3),
    ('27', 'Raybag Monday Santhe', 'Raybag', 'Calendar.MONDAY', 'Grape varieties & Pomegranates', 16.59, 74.78),
    ('28', 'Saundatti Wednesday Shandy', 'Saundatti', 'Calendar.WEDNESDAY', 'Yellamma Temple artifacts', 15.77, 75.12),
    ('29', 'Kittur Friday Market', 'Kittur', 'Calendar.FRIDAY', 'Historical replicas & Local pottery', 15.6, 74.79),
    ('30', 'Hukkeri Tuesday Santhe', 'Hukkeri', 'Calendar.TUESDAY', 'Chilli powder & Spices', 16.23, 74.6),
    ('31', 'Gadag Sunday Bazaar', 'Gadag', 'Calendar.SUNDAY', 'Printing supplies & Sunflower oil', 15.42, 75.63),
    ('32', 'Ron Monday Santhe', 'Ron', 'Calendar.MONDAY', 'Greens & Local Millets', 15.7, 75.73),
    ('33', 'Naragund Wednesday Bazaar', 'Naragund', 'Calendar.WEDNESDAY', 'Wheat & Pulses', 15.72, 75.38),
    ('34', 'Shirahatti Friday Shandy', 'Shirahatti', 'Calendar.FRIDAY', 'Hand-woven blankets', 15.23, 75.58),
    ('35', 'Mundargi Tuesday Santhe', 'Mundargi', 'Calendar.TUESDAY', 'Groundnuts & Jowar', 15.21, 75.88),
    ('36', 'Laxmeshwar Thursday Bazaar', 'Laxmeshwar', 'Calendar.THURSDAY', 'Incense sticks & Oil seeds', 15.13, 75.47),
    ('37', 'Haveri Sunday Shandy', 'Haveri', 'Calendar.SUNDAY', 'Cardamom Garlands', 14.79, 75.4),
    ('38', 'Ranebennur Monday Market', 'Ranebennur', 'Calendar.MONDAY', 'Hybrid seeds & Grains', 14.62, 75.63),
    ('39', 'Hirekerur Wednesday Santhe', 'Hirekerur', 'Calendar.WEDNESDAY', 'Arecanut & Banana', 14.47, 75.38),
    ('40', 'Shiggaon Friday Shandy', 'Shiggaon', 'Calendar.FRIDAY', 'Vermicompost & Saplings', 14.99, 75.23),
    ('41', 'Savanur Tuesday Market', 'Savanur', 'Calendar.TUESDAY', 'Betel nuts & Flowers', 14.97, 75.35),
    ('42', 'Hangal Thursday Santhe', 'Hangal', 'Calendar.THURSDAY', 'Temple jewelry & Vegetables', 14.76, 75.13),
    ('43', 'Kalghatgi Monday Shandy', 'Kalghatgi', 'Calendar.MONDAY', 'Wooden cradles & Carts', 15.18, 74.97),
    ('44', 'Kundgol Wednesday Bazaar', 'Kundgol', 'Calendar.WEDNESDAY', 'Onions & Garlic', 15.25, 75.25),
    ('45', 'Navalgund Friday Santhe', 'Navalgund', 'Calendar.FRIDAY', 'Dhurries (Rugs) & Cotton', 15.55, 75.37),
    ('46', 'Bagalkot Sunday Shandy', 'Bagalkot', 'Calendar.SUNDAY', 'Woven baskets & Earthenware', 16.18, 75.7),
    ('47', 'Badami Monday Market', 'Badami', 'Calendar.MONDAY', 'Stone carvings & Pomegranates', 15.92, 75.68),
    ('48', 'Hunagund Wednesday Santhe', 'Hunagund', 'Calendar.WEDNESDAY', 'Red granite crafts', 16.07, 76.05),
    ('49', 'Jamkhandi Friday Bazaar', 'Jamkhandi', 'Calendar.FRIDAY', 'Grapes & Sugarcane implements', 16.51, 75.29),
    ('50', 'Mudhol Tuesday Shandy', 'Mudhol', 'Calendar.TUESDAY', 'Mudhol Hound artifacts', 16.35, 75.28),
    ('51', 'Bilagi Thursday Santhe', 'Bilagi', 'Calendar.THURSDAY', 'Limestone & Local crops', 16.34, 75.62),
    ('52', 'Vijayapura Sunday Market', 'Vijayapura', 'Calendar.SUNDAY', 'Grapes & Dry fruits', 16.8302, 75.71),
    ('53', 'Indi Monday Bazaar', 'Indi', 'Calendar.MONDAY', 'Lemons & Jowar', 17.17, 75.97),
    ('54', 'Sindagi Wednesday Santhe', 'Sindagi', 'Calendar.WEDNESDAY', 'Agricultural seeds', 16.92, 76.23),
    ('55', 'Muddebihal Friday Shandy', 'Muddebihal', 'Calendar.FRIDAY', 'Coarse grains & Pulses', 16.33, 76.13),
    ('56', 'Basavana Bagewadi Tuesday Market', 'Basavana Bagewadi', 'Calendar.TUESDAY', 'Spiritual books & Artifacts', 16.58, 75.98),
    ('57', 'Kalaburagi Sunday Bazaar', 'Kalaburagi', 'Calendar.SUNDAY', 'Toor Dal & Banjara embroidery', 17.3297, 76.8343),
    ('58', 'Aland Monday Santhe', 'Aland', 'Calendar.MONDAY', 'Handloom blankets', 17.56, 76.57),
    ('59', 'Afzalpur Wednesday Shandy', 'Afzalpur', 'Calendar.WEDNESDAY', 'Watermelons & Millets', 17.2, 76.35),
    ('60', 'Jevargi Friday Market', 'Jevargi', 'Calendar.FRIDAY', 'River fish & Grains', 17.02, 76.77),
    ('61', 'Chittapur Tuesday Bazaar', 'Chittapur', 'Calendar.TUESDAY', 'Shahabad stones', 17.12, 77.08),
    ('62', 'Sedam Thursday Santhe', 'Sedam', 'Calendar.THURSDAY', 'Cement artifacts & Pulses', 17.18, 77.28),
    ('63', 'Chincholi Sunday Shandy', 'Chincholi', 'Calendar.SUNDAY', 'Herbal medicines', 17.47, 77.43),
    ('64', 'Yadgir Monday Bazaar', 'Yadgir', 'Calendar.MONDAY', 'Groundnuts & Cotton', 16.76, 77.13),
    ('65', 'Shahapur Wednesday Santhe', 'Shahapur', 'Calendar.WEDNESDAY', 'Rice & Vegetables', 16.7, 76.83),
    ('66', 'Shorapur Friday Shandy', 'Shorapur', 'Calendar.FRIDAY', 'Historical paintings', 16.52, 76.76),
    ('67', 'Raichur Sunday Market', 'Raichur', 'Calendar.SUNDAY', 'Fine Rice (Sona Masuri)', 16.212, 77.3439),
    ('68', 'Manvi Monday Santhe', 'Manvi', 'Calendar.MONDAY', 'Cotton & Chillies', 15.98, 77.05),
    ('69', 'Sindhanur Wednesday Bazaar', 'Sindhanur', 'Calendar.WEDNESDAY', 'Paddy & Farm machinery', 15.78, 76.76),
    ('70', 'Devadurga Friday Shandy', 'Devadurga', 'Calendar.FRIDAY', 'Local millets', 16.42, 76.93),
    ('71', 'Lingsugur Tuesday Market', 'Lingsugur', 'Calendar.TUESDAY', 'Gold jewelry & Spices', 16.16, 76.52),
    ('72', 'Koppal Sunday Shandy', 'Koppal', 'Calendar.SUNDAY', 'Kinnal Toys & Crafts', 15.34, 76.15),
    ('73', 'Gangavathi Monday Bazaar', 'Gangavathi', 'Calendar.MONDAY', 'Rice varieties', 15.43, 76.53),
    ('74', 'Yelburga Wednesday Santhe', 'Yelburga', 'Calendar.WEDNESDAY', 'Jowar & Sunflower', 15.6, 76.01),
    ('75', 'Kushtagi Friday Shandy', 'Kushtagi', 'Calendar.FRIDAY', 'Sheep & Goat market', 15.76, 76.19),
    ('76', 'Ballari Sunday Bazaar', 'Ballari', 'Calendar.SUNDAY', 'Jeans & Cotton textiles', 15.1394, 76.9214),
    ('77', 'Hosapete Monday Market', 'Hosapete', 'Calendar.MONDAY', 'Hampi souvenirs', 15.2689, 76.3909),
    ('78', 'Sandur Friday Shandy', 'Sandur', 'Calendar.FRIDAY', 'Iron ore crafts & Embroidery', 15.08, 76.55),
    ('79', 'Siruguppa Tuesday Santhe', 'Siruguppa', 'Calendar.TUESDAY', 'Paddy & River fish', 15.62, 76.9),
    ('80', 'Hadagali Thursday Bazaar', 'Hadagali', 'Calendar.THURSDAY', 'Jasmine flowers', 15.02, 75.95),
    ('81', 'Kudligi Monday Shandy', 'Kudligi', 'Calendar.MONDAY', 'Groundnuts & Pulses', 14.9, 76.38),
    ('82', 'Shivamogga Sunday Market', 'Shivamogga', 'Calendar.SUNDAY', 'Arecanut & Spices', 13.9299, 75.5681),
    ('83', 'Bhadravathi Monday Shandy', 'Bhadravathi', 'Calendar.MONDAY', 'Iron and Steel artifacts', 13.84, 75.7),
    ('84', 'Shikaripura Tuesday Bazaar', 'Shikaripura', 'Calendar.TUESDAY', 'Paddy & Arecanut', 14.27, 75.35),
    ('85', 'Soraba Monday Santhe', 'Soraba', 'Calendar.MONDAY', 'Sandalwood & Ivory', 14.38, 75.09),
    ('86', 'Hosanagara Tuesday Shandy', 'Hosanagara', 'Calendar.TUESDAY', 'Forest produce', 13.92, 75.07),
    ('87', 'Thirthahalli Thursday Market', 'Thirthahalli', 'Calendar.THURSDAY', 'Arecanut & Fish', 13.69, 75.24),
    ('88', 'Chikkamagaluru Sunday Bazaar', 'Chikkamagaluru', 'Calendar.SUNDAY', 'Coffee beans & Spices', 13.3161, 75.772),
    ('89', 'Kadur Monday Santhe', 'Kadur', 'Calendar.MONDAY', 'Coconuts & Pulses', 13.55, 76.01),
    ('90', 'Tarikere Wednesday Shandy', 'Tarikere', 'Calendar.WEDNESDAY', 'Timber & Fruits', 13.71, 75.81),
    ('91', 'Mudigere Friday Market', 'Mudigere', 'Calendar.FRIDAY', 'Tea & Cardamom', 13.13, 75.63),
    ('92', 'Sringeri Thursday Santhe', 'Sringeri', 'Calendar.THURSDAY', 'Spiritual items & Flowers', 13.42, 75.25),
    ('93', 'Hassan Sunday Market', 'Hassan', 'Calendar.SUNDAY', 'Potatoes & Coffee', 13.0072, 76.1029),
    ('94', 'Arsikere Monday Shandy', 'Arsikere', 'Calendar.MONDAY', 'Coconut oil & Copra', 13.31, 76.26),
    ('95', 'Belur Wednesday Bazaar', 'Belur', 'Calendar.WEDNESDAY', 'Stone artifacts', 13.16, 75.86),
    ('96', 'Channarayapatna Tuesday Santhe', 'Channarayapatna', 'Calendar.TUESDAY', 'Ghee & Butter', 12.9, 76.39),
    ('97', 'Sakleshpur Monday Market', 'Sakleshpur', 'Calendar.MONDAY', 'Cardamom & Pepper', 12.89, 75.78),
    ('98', 'Bantwal Sunday Shandy', 'Bantwal', 'Calendar.SUNDAY', 'Coconut & Arecanut', 12.89, 75.03),
    ('99', 'Puttur Wednesday Bazaar', 'Puttur', 'Calendar.WEDNESDAY', 'Cashews & Spices', 12.72, 75.2),
    ('100', 'Sullia Friday Santhe', 'Sullia', 'Calendar.FRIDAY', 'Rubber & Cocoa', 12.56, 75.39),
    ('101', 'Udupi Sunday Market', 'Udupi', 'Calendar.SUNDAY', 'Spices & Mattu Gulla Brinjal', 13.3409, 74.7473),
    ('102', 'Karkala Wednesday Shandy', 'Karkala', 'Calendar.WEDNESDAY', 'Stone statues', 13.21, 74.99),
    ('103', 'Davanagere Sunday Bazaar', 'Davanagere', 'Calendar.SUNDAY', 'Butter Dosa ingredients', 14.4644, 75.9218),
    ('104', 'Harihara Monday Shandy', 'Harihara', 'Calendar.MONDAY', 'Handloom fabrics', 14.51, 75.8),
    ('105', 'Channagiri Wednesday Santhe', 'Channagiri', 'Calendar.WEDNESDAY', 'Arecanut & Maize', 14.02, 75.93),
    ('106', 'Chitradurga Sunday Market', 'Chitradurga', 'Calendar.SUNDAY', 'Onions & Oilseeds', 14.2251, 76.402),
    ('107', 'Challakere Monday Bazaar', 'Challakere', 'Calendar.MONDAY', 'Groundnuts & Sheep', 14.31, 76.65),
    ('108', 'Hiriyur Wednesday Shandy', 'Hiriyur', 'Calendar.WEDNESDAY', 'Coconuts & Jaggery', 13.94, 76.61),
    ('109', 'Tumakuru Sunday Bazaar', 'Tumakuru', 'Calendar.SUNDAY', 'Coconuts & Groundnuts', 13.3392, 77.114),
    ('110', 'Tiptur Thursday Santhe', 'Tiptur', 'Calendar.THURSDAY', 'Copra (Dry Coconut)', 13.26, 76.48),
    ('111', 'Kunigal Tuesday Shandy', 'Kunigal', 'Calendar.TUESDAY', 'Silk cocoons', 13.02, 77.03),
    ('112', 'Kolar Sunday Market', 'Kolar', 'Calendar.SUNDAY', 'Milk & Tomatoes', 13.1367, 78.1292),
    ('113', 'Bangarapet Monday Shandy', 'Bangarapet', 'Calendar.MONDAY', 'Gobi Manchurian & Chaats', 12.98, 78.18),
    ('114', 'Chikballapur Sunday Bazaar', 'Chikballapur', 'Calendar.SUNDAY', 'Silk & Grapes', 13.4323, 77.7283),
    ('115', 'Chintamani Wednesday Santhe', 'Chintamani', 'Calendar.WEDNESDAY', 'Silk & Tomatoes', 13.4, 78.06),
    ('116', 'Ramanagara Sunday Shandy', 'Ramanagara', 'Calendar.SUNDAY', 'Silk Cocoons', 12.716, 77.276),
    ('117', 'Channapatna Monday Bazaar', 'Channapatna', 'Calendar.MONDAY', 'Wooden Toys', 12.65, 77.21),
    ('118', 'Kanakapura Wednesday Santhe', 'Kanakapura', 'Calendar.WEDNESDAY', 'Silk & Vegetables', 12.54, 77.42),
    ('119', 'Mandya Sunday Market', 'Mandya', 'Calendar.SUNDAY', 'Jaggery & Sugarcane', 12.5218, 76.8951),
    ('120', 'Maddur Monday Shandy', 'Maddur', 'Calendar.MONDAY', 'Maddur Vada & Silk', 12.58, 77.04),
    ('121', 'Srirangapatna Friday Bazaar', 'Srirangapatna', 'Calendar.FRIDAY', 'Spiritual items', 12.42, 76.69),
    ('122', 'Nanjangud Monday Shandy', 'Nanjangud', 'Calendar.MONDAY', 'Rasabale (Banana)', 12.11, 76.67),
    ('123', 'Hunsur Friday Bazaar', 'Hunsur', 'Calendar.FRIDAY', 'Tobacco & Timber', 12.31, 76.28),
    ('124', 'Chamarajanagar Sunday Shandy', 'Chamarajanagar', 'Calendar.SUNDAY', 'Turmeric & Forest produce', 11.9261, 76.939),
    ('125', 'Gundlupet Monday Market', 'Gundlupet', 'Calendar.MONDAY', 'Flowers & Vegetables', 11.81, 76.68),
    ('126', 'Kollegal Wednesday Santhe', 'Kollegal', 'Calendar.WEDNESDAY', 'Silk & Handlooms', 12.15, 77.11),
    ('127', 'Madikeri Sunday Shandy', 'Madikeri', 'Calendar.SUNDAY', 'Coffee & Honey', 12.4244, 75.7382),
    ('128', 'Virajpet Monday Market', 'Virajpet', 'Calendar.MONDAY', 'Spices & Pork products', 12.19, 75.8),
    ('129', 'Doddaballapur Sunday Bazaar', 'Doddaballapur', 'Calendar.SUNDAY', 'Silk weaving items', 13.29, 77.53),
    ('130', 'Devanahalli Monday Shandy', 'Devanahalli', 'Calendar.MONDAY', 'Flowers & Fruits', 13.24, 77.71),
    ('131', 'Hoskote Wednesday Bazaar', 'Hoskote', 'Calendar.WEDNESDAY', 'Vegetables & Poultry', 13.07, 77.8),
    ('132', 'Nelamangala Friday Santhe', 'Nelamangala', 'Calendar.FRIDAY', 'Grains & Vegetables', 13.1, 77.39),
    ('133', 'Anekal Sunday Bazaar', 'Anekal', 'Calendar.SUNDAY', 'Silk & Ragi', 12.71, 77.69),
    ('134', 'Bidar Sunday Market', 'Bidar', 'Calendar.SUNDAY', 'Bidriware & Pulses', 17.9104, 77.5199),
    ('135', 'Bhalki Monday Shandy', 'Bhalki', 'Calendar.MONDAY', 'Handicrafts & Grains', 18.03, 77.21),
    ('136', 'Homnabad Wednesday Bazaar', 'Homnabad', 'Calendar.WEDNESDAY', 'Traditional snacks', 17.77, 77.13),
    ('137', 'Basavakalyan Saturday Shandy', 'Basavakalyan', 'Calendar.SATURDAY', 'Spiritual items', 17.87, 76.95),
    ('138', 'Gajendragad Thursday Santhe', 'Gajendragad', 'Calendar.THURSDAY', 'Handloom Sarees', 15.73, 75.97),
    ('139', 'Mundargi Tuesday Shandy', 'Mundargi', 'Calendar.TUESDAY', 'Groundnut oil', 15.21, 75.88),
    ('140', 'Laxmeshwar Thursday Shandy', 'Laxmeshwar', 'Calendar.THURSDAY', 'Incense sticks', 15.13, 75.47),
    ('141', 'Savanur Tuesday Shandy', 'Savanur', 'Calendar.TUESDAY', 'Betel leaves', 14.97, 75.35),
    ('142', 'Shiggaon Friday Shandy', 'Shiggaon', 'Calendar.FRIDAY', 'Seedlings', 14.99, 75.23),
    ('143', 'Hangal Thursday Shandy', 'Hangal', 'Calendar.THURSDAY', 'Vegetables', 14.76, 75.13),
    ('144', 'Hirekerur Wednesday Shandy', 'Hirekerur', 'Calendar.WEDNESDAY', 'Arecanut', 14.47, 75.38),
    ('145', 'Rattihalli Monday Shandy', 'Rattihalli', 'Calendar.MONDAY', 'Grains', 14.42, 75.52),
    ('146', 'Honnali Friday Shandy', 'Honnali', 'Calendar.FRIDAY', 'River fish', 14.24, 75.64),
    ('147', 'Channagiri Wednesday Shandy', 'Channagiri', 'Calendar.WEDNESDAY', 'Arecanut', 14.02, 75.93),
    ('148', 'Jagalur Tuesday Shandy', 'Jagalur', 'Calendar.TUESDAY', 'Millets', 14.53, 76.34),
    ('149', 'Molakalmuru Thursday Shandy', 'Molakalmuru', 'Calendar.THURSDAY', 'Silk Sarees', 14.73, 76.75),
    ('150', 'Holalkere Friday Shandy', 'Holalkere', 'Calendar.FRIDAY', 'Onions', 14.04, 76.18),
    ('151', 'Hosadurga Tuesday Shandy', 'Hosadurga', 'Calendar.TUESDAY', 'Coconuts', 13.8, 76.29),
    ('152', 'Pavagada Monday Shandy', 'Pavagada', 'Calendar.MONDAY', 'Groundnuts', 14.1, 77.27),
    ('153', 'Madhugiri Friday Shandy', 'Madhugiri', 'Calendar.FRIDAY', 'Pomegranates', 13.66, 77.21),
    ('154', 'Sira Wednesday Shandy', 'Sira', 'Calendar.WEDNESDAY', 'Groundnuts', 13.74, 76.91),
    ('155', 'Gubbi Monday Shandy', 'Gubbi', 'Calendar.MONDAY', 'Coconuts', 13.31, 76.94),
    ('156', 'Turuvekere Sunday Shandy', 'Turuvekere', 'Calendar.SUNDAY', 'Coconuts', 13.16, 76.66),
    ('157', 'Chiknayakanhalli Friday Shandy', 'Chiknayakanhalli', 'Calendar.FRIDAY', 'Coconuts', 13.42, 76.62),
    ('158', 'Koratagere Wednesday Shandy', 'Koratagere', 'Calendar.WEDNESDAY', 'Vegetables', 13.52, 77.23),
    ('159', 'Magadi Friday Shandy', 'Magadi', 'Calendar.FRIDAY', 'Silk', 12.96, 77.23),
    ('160', 'Kanakapura Wednesday Shandy', 'Kanakapura', 'Calendar.WEDNESDAY', 'Silk', 12.54, 77.42),
    ('161', 'Malavalli Wednesday Shandy', 'Malavalli', 'Calendar.WEDNESDAY', 'Silk', 12.38, 77.05),
    ('162', 'Pandavapura Tuesday Shandy', 'Pandavapura', 'Calendar.TUESDAY', 'Jaggery', 12.49, 76.67),
    ('163', 'Nagamangala Thursday Shandy', 'Nagamangala', 'Calendar.THURSDAY', 'Silk', 12.82, 76.75),
    ('164', 'Krishnarajapete Sunday Shandy', 'Krishnarajapete', 'Calendar.SUNDAY', 'Silk', 12.66, 76.49),
    ('165', 'K.R. Nagar Tuesday Shandy', 'K.R. Nagar', 'Calendar.TUESDAY', 'Paddy', 12.44, 76.38),
    ('166', 'Periyapatna Thursday Shandy', 'Periyapatna', 'Calendar.THURSDAY', 'Tobacco', 12.34, 76.1),
    ('167', 'H.D. Kote Sunday Shandy', 'H.D. Kote', 'Calendar.SUNDAY', 'Forest produce', 12.08, 76.33),
    ('168', 'Saraguru Monday Shandy', 'Saraguru', 'Calendar.MONDAY', 'Forest produce', 12.01, 76.38),
    ('169', 'Gundlupet Monday Shandy', 'Gundlupet', 'Calendar.MONDAY', 'Flowers', 11.81, 76.68),
    ('170', 'Yelandur Friday Shandy', 'Yelandur', 'Calendar.FRIDAY', 'Silk', 12.06, 77.03),
    ('171', 'Hanur Tuesday Shandy', 'Hanur', 'Calendar.TUESDAY', 'Forest produce', 12.08, 77.29),
    ('172', 'Srinivaspur Tuesday Shandy', 'Srinivaspur', 'Calendar.TUESDAY', 'Mangoes', 13.34, 78.21),
    ('173', 'Mulbagal Friday Shandy', 'Mulbagal', 'Calendar.FRIDAY', 'Milk', 13.16, 78.39),
    ('174', 'Malur Wednesday Shandy', 'Malur', 'Calendar.WEDNESDAY', 'Vegetables', 13.0, 77.94),
    ('175', 'Gauribidanur Monday Shandy', 'Gauribidanur', 'Calendar.MONDAY', 'Grains', 13.61, 77.52),
    ('176', 'Sidlaghatta Friday Shandy', 'Sidlaghatta', 'Calendar.FRIDAY', 'Silk', 13.39, 77.86),
    ('177', 'Bagepalli Tuesday Shandy', 'Bagepalli', 'Calendar.TUESDAY', 'Grains', 13.78, 77.79),
    ('178', 'Gudibanda Thursday Shandy', 'Gudibanda', 'Calendar.THURSDAY', 'Grains', 13.67, 77.67),
    ('179', 'Ajjampura Sunday Shandy', 'Ajjampura', 'Calendar.SUNDAY', 'Cattle', 13.72, 76.12),
    ('180', 'Koppa Tuesday Shandy', 'Koppa', 'Calendar.TUESDAY', 'Tea', 13.53, 75.35),
    ('181', 'Narasimharajapura Sunday Shandy', 'Narasimharajapura', 'Calendar.SUNDAY', 'Arecanut', 13.59, 75.52),
    ('182', 'Alur Monday Shandy', 'Alur', 'Calendar.MONDAY', 'Coffee', 12.98, 75.98),
    ('183', 'Arkalgud Sunday Shandy', 'Arkalgud', 'Calendar.SUNDAY', 'Coconut', 12.76, 76.06),
    ('184', 'Holenarasipura Thursday Shandy', 'Holenarasipura', 'Calendar.THURSDAY', 'Tobacco', 12.79, 76.23),
    ('185', 'Belur Wednesday Shandy', 'Belur', 'Calendar.WEDNESDAY', 'Stone artifacts', 13.16, 75.86),
    ('186', 'Moodabidri Tuesday Shandy', 'Moodabidri', 'Calendar.TUESDAY', 'Cashews', 13.07, 74.99),
    ('187', 'Beltangady Monday Shandy', 'Beltangady', 'Calendar.MONDAY', 'Arecanut', 13.0, 75.3),
    ('188', 'Brahmavar Wednesday Shandy', 'Brahmavar', 'Calendar.WEDNESDAY', 'Fish', 13.42, 74.74),
    ('189', 'Byndoor Friday Shandy', 'Byndoor', 'Calendar.FRIDAY', 'Fish', 13.87, 74.62),
    ('190', 'Hebri Tuesday Shandy', 'Hebri', 'Calendar.TUESDAY', 'Forest produce', 13.46, 75.02),
    ('191', 'Kaup Thursday Shandy', 'Kaup', 'Calendar.THURSDAY', 'Fish', 13.22, 74.74),
    ('192', 'Karkala Wednesday Shandy', 'Karkala', 'Calendar.WEDNESDAY', 'Stone statues', 13.21, 74.99),
    ('193', 'Lingsugur Tuesday Shandy', 'Lingsugur', 'Calendar.TUESDAY', 'Gold', 16.16, 76.52),
    ('194', 'Devadurga Friday Shandy', 'Devadurga', 'Calendar.FRIDAY', 'Millets', 16.42, 76.93),
    ('195', 'Sindhanur Wednesday Shandy', 'Sindhanur', 'Calendar.WEDNESDAY', 'Paddy', 15.78, 76.76),
    ('196', 'Manvi Monday Shandy', 'Manvi', 'Calendar.MONDAY', 'Cotton', 15.98, 77.05),
    ('197', 'Sirwar Tuesday Shandy', 'Sirwar', 'Calendar.TUESDAY', 'Paddy', 16.12, 77.03),
    ('198', 'Maski Thursday Shandy', 'Maski', 'Calendar.THURSDAY', 'Historical artifacts', 15.96, 76.66),
    ('199', 'Kushtagi Friday Shandy', 'Kushtagi', 'Calendar.FRIDAY', 'Sheep', 15.76, 76.19),
    ('200', 'Yelburga Wednesday Shandy', 'Yelburga', 'Calendar.WEDNESDAY', 'Jowar', 15.6, 76.01),
    ('201', 'Kanakagiri Monday Shandy', 'Kanakagiri', 'Calendar.MONDAY', 'Paddy', 15.58, 76.41),
    ('202', 'Karatagi Tuesday Shandy', 'Karatagi', 'Calendar.TUESDAY', 'Paddy', 15.59, 76.69),
    ('203', 'Kuknoor Thursday Shandy', 'Kuknoor', 'Calendar.THURSDAY', 'Jowar', 15.46, 76.01),
    ('204', 'Sandur Friday Shandy', 'Sandur', 'Calendar.FRIDAY', 'Iron ore crafts', 15.08, 76.55),
    ('205', 'Kampli Wednesday Shandy', 'Kampli', 'Calendar.WEDNESDAY', 'Jaggery', 15.4, 76.61),
    ('206', 'Kurugodu Thursday Shandy', 'Kurugodu', 'Calendar.THURSDAY', 'Paddy', 15.34, 76.83),
    ('207', 'Siruguppa Tuesday Shandy', 'Siruguppa', 'Calendar.TUESDAY', 'Paddy', 15.62, 76.9),
    ('208', 'Hadagali Thursday Shandy', 'Hadagali', 'Calendar.THURSDAY', 'Jasmine', 15.02, 75.95),
    ('209', 'Hagaribommanahalli Sunday Shandy', 'Hagaribommanahalli', 'Calendar.SUNDAY', 'Millets', 15.09, 76.2),
    ('210', 'Kotturu Wednesday Shandy', 'Kotturu', 'Calendar.WEDNESDAY', 'Spiritual items', 14.82, 76.22),
    ('211', 'Harapanahalli Tuesday Shandy', 'Harapanahalli', 'Calendar.TUESDAY', 'Butter', 14.79, 75.99),
    ('212', 'Nidagundi Shandy', 'Nidagundi', 'Calendar.THURSDAY', 'Crops', 16.22, 75.94),
    ('213', 'Kolhar Tuesday Shandy', 'Kolhar', 'Calendar.TUESDAY', 'Curd & Fish', 16.28, 75.82),
    ('214', 'Babaleshwar Shandy', 'Babaleshwar', 'Calendar.MONDAY', 'Grapes', 16.72, 75.61),
    ('215', 'Tikota Sunday Shandy', 'Tikota', 'Calendar.SUNDAY', 'Grapes', 16.85, 75.52),
    ('216', 'Chadchan Monday Shandy', 'Chadchan', 'Calendar.MONDAY', 'Grains', 17.24, 75.5),
    ('217', 'Yaragatti Shandy', 'Yaragatti', 'Calendar.FRIDAY', 'Agriculture', 15.98, 74.96),
    ('218', 'Kalasa Friday Shandy', 'Kalasa', 'Calendar.FRIDAY', 'Tea & Spices', 13.23, 75.36),
    ('219', 'Mulki Sunday Shandy', 'Mulki', 'Calendar.SUNDAY', 'Fish', 13.08, 74.79)
]

def update_repository(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    new_lines = []
    in_static_santhes = False
    added = False
    
    for line in lines:
        if 'private val staticSanthes = listOf(' in line:
            in_static_santhes = True
            new_lines.append(line)
            for s in santhes_list:
                id, name, village, day, spec, lat, lng = s
                new_lines.append(f'        Santhe("{id}", "{name}", "{village}", {day}, "{spec}", {lat}, {lng}),\n')
            added = True
            continue
        
        if in_static_santhes:
            if ')' in line and line.strip().endswith(')'):
                in_static_santhes = False
                new_lines.append(line)
            continue
        
        new_lines.append(line)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

update_repository(r'C:\Users\krish\.gemini\antigravity\playground\lunar-hawking\app\src\main\java\com\example\santheconnect\data\MarketRepository.kt')
print("Updated successfully")
